Bugfix/20220108/ethereum compatible replayattack
vision-consensus/vision-core pull request #109
Opened 2022-01-10 15:29 UTC by darylccc

**What does this PR do?**

**Why are these changes required?**

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

2022-01-11 16:09 UTC, vchain007 requested changes

2022-01-11 16:15 UTC, vchain007 commented on framework/src/main/java/org/vision/core/db/Manager.java
> +    validateP2pVersion(trxCap);
can we add validateEthereumRlpParseVisionTransaction(trxCap)

this function can drop out transaction which bad person change vision transaction content not real from rlpdata

2022-01-12 04:33 UTC, vchain007 approved these changes

2022-01-12 05:50 UTC, darylccc commented on framework/src/main/java/org/vision/core/db/Manager.java
> +    validateP2pVersion(trxCap);
This function is already included in the validateSignature method

2022-01-12 06:23 UTC, linusoutman approved these changes

2022-01-12 06:25 UTC, merged