Feature/function optimize vtest
vision-consensus/vision-core pull request #96
Opened 2021-12-27 13:58 UTC by darylccc

**What does this PR do?**

**Why are these changes required?**

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

2021-12-27 15:40 UTC, vchain007 commented on framework/src/main/resources/config.conf
> +debug.feature.effect = {
debug.feature.effect -> debug.feature.effectblocknum

2021-12-27 15:40 UTC, vchain007 commented on framework/src/main/java/org/vision/core/config/args/Args.java
> +    PARAMETER.spreadMintUnlimitedPledge =
spreadMintUnlimitedPledge -> spreadMintUnlimitedPledgeEffectBlocknum

2021-12-27 15:40 UTC, vchain007 commented on framework/src/main/java/org/vision/core/config/args/Args.java
> +    PARAMETER.witnessSort =
witnessSort -> witnessSortBlocknum

2021-12-27 15:40 UTC, vchain007 commented on common/src/main/java/org/vision/core/Constant.java
> +  public static final String DEBUG_FEATURE_EFFECT_SPREADMINT_UNLIMITEDPLEDGE  = "debug.feature.effect.spreadMint.unlimitedPledge";
DEBUG_FEATURE_EFFECT_SPREADMINT_UNLIMITEDPLEDGE -> DEBUG_FEATURE_EFFECTBLOCKNUM_SPREADMINT_UNLIMITEDPLEDGE

debug.feature.effect.spreadMint.unlimitedPledge -> debug.feature.effectblocknum.spreadMint.unlimitedPledge

2021-12-27 15:40 UTC, vchain007 commented on common/src/main/java/org/vision/core/Constant.java
> +  public static final String DEBUG_FEATURE_EFFECT_WITNESS_SORT  = "debug.feature.effect.witness.sort";
DEBUG_FEATURE_EFFECT_WITNESS_SORT -> DEBUG_FEATURE_EFFECTBLOCKNUM_WITNESS_SORT

debug.feature.effect.witness.sort -> debug.feature.effectblocknum.witness.sort

2021-12-27 15:40 UTC, vchain007 commented on executor/src/main/java/org/vision/core/actuator/FreezeBalanceActuator.java
> +            throw new ContractValidateException("It's not time to modify parentAddress.");
u 'd better add exact remaining time

2021-12-27 15:40 UTC, vchain007 commented on executor/src/main/java/org/vision/core/actuator/FreezeBalanceActuator.java
> +            throw new ContractValidateException("It's not time to re-freeze.");
u 'd better add exact remaining time

2021-12-28 02:00 UTC, darylccc commented on framework/src/main/java/org/vision/core/config/args/Args.java
> +    PARAMETER.witnessSort =
witnessSortEffectBlockNum

2021-12-28 06:27 UTC, linusoutman requested changes
approved

2021-12-28 06:28 UTC, linusoutman approved these changes

2021-12-28 06:28 UTC, merged